apiVersion: v1
kind: Service
metadata:
  name: orderhub-api-service
  namespace: orderhub
spec:
  type: ClusterIP
  selector:
    app: orderhub-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
